//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagingToolkit.SmartGateway.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MessagingToolkit.SmartGateway.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Available Channel - *.
        /// </summary>
        internal static string AnyChannels {
            get {
                return ResourceManager.GetString("AnyChannels", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap application_sidebar_list {
            get {
                object obj = ResourceManager.GetObject("application_sidebar_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessagingToolkit SmartGateway.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap archive {
            get {
                object obj = ResourceManager.GetObject("archive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap channel {
            get {
                object obj = ResourceManager.GetObject("channel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap contacts {
            get {
                object obj = ResourceManager.GetObject("contacts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap email_delete {
            get {
                object obj = ResourceManager.GetObject("email_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap email_forward {
            get {
                object obj = ResourceManager.GetObject("email_forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap email_reply {
            get {
                object obj = ResourceManager.GetObject("email_reply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit1 {
            get {
                object obj = ResourceManager.GetObject("exit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_horizontal {
            get {
                object obj = ResourceManager.GetObject("folder_horizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap groups {
            get {
                object obj = ResourceManager.GetObject("groups", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help32 {
            get {
                object obj = ResourceManager.GetObject("help32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hide_me {
            get {
                object obj = ResourceManager.GetObject("hide_me", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap inbox {
            get {
                object obj = ResourceManager.GetObject("inbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information1 {
            get {
                object obj = ResourceManager.GetObject("information1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap license {
            get {
                object obj = ResourceManager.GetObject("license", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manual {
            get {
                object obj = ResourceManager.GetObject("manual", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap message_reply {
            get {
                object obj = ResourceManager.GetObject("message_reply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap messages {
            get {
                object obj = ResourceManager.GetObject("messages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap messenger {
            get {
                object obj = ResourceManager.GetObject("messenger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap messenger_app {
            get {
                object obj = ResourceManager.GetObject("messenger_app", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mobile_phone_cast {
            get {
                object obj = ResourceManager.GetObject("mobile_phone_cast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator group name is not allowed.
        /// </summary>
        internal static string MsgAdminGroupNameNotAllowed {
            get {
                return ResourceManager.GetString("MsgAdminGroupNameNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator user name is not allowed.
        /// </summary>
        internal static string MsgAdminUserNameNotAllowed {
            get {
                return ResourceManager.GetString("MsgAdminUserNameNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply settings (Manual restart required) ?.
        /// </summary>
        internal static string MsgApplySettings {
            get {
                return ResourceManager.GetString("MsgApplySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto response text is required.
        /// </summary>
        internal static string MsgAutoResponseTextRequired {
            get {
                return ResourceManager.GetString("MsgAutoResponseTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to delete gateway [{0}]?.
        /// </summary>
        internal static string MsgConfirmDeleteGateway {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete group - {0} ?.
        /// </summary>
        internal static string MsgConfirmDeleteGroup {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to delete message?.
        /// </summary>
        internal static string MsgConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to delete messenger [{0}]?.
        /// </summary>
        internal static string MsgConfirmDeleteMessenger {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteMessenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user - {0}?.
        /// </summary>
        internal static string MsgConfirmDeleteUser {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset message settings?.
        /// </summary>
        internal static string MsgConfirmResetMessageSettings {
            get {
                return ResourceManager.GetString("MsgConfirmResetMessageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message content is required.
        /// </summary>
        internal static string MsgContentRequired {
            get {
                return ResourceManager.GetString("MsgContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database table column name is required.
        /// </summary>
        internal static string MsgDbTableRequired {
            get {
                return ResourceManager.GetString("MsgDbTableRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database user name is required.
        /// </summary>
        internal static string MsgDbUserNameRequired {
            get {
                return ResourceManager.GetString("MsgDbUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database user password is required.
        /// </summary>
        internal static string MsgDbUserPasswordRequired {
            get {
                return ResourceManager.GetString("MsgDbUserPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination number column name is required.
        /// </summary>
        internal static string MsgDestNoColNameRequired {
            get {
                return ResourceManager.GetString("MsgDestNoColNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSN is required.
        /// </summary>
        internal static string MsgDsnRequired {
            get {
                return ResourceManager.GetString("MsgDsnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already in use. Continue with saving?.
        /// </summary>
        internal static string MsgDuplicateComPort {
            get {
                return ResourceManager.GetString("MsgDuplicateComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address cannot be empty.
        /// </summary>
        internal static string MsgEmailAddressRequired {
            get {
                return ResourceManager.GetString("MsgEmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email settings are saved successfully.
        /// </summary>
        internal static string MsgEmailConfigSaved {
            get {
                return ResourceManager.GetString("MsgEmailConfigSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email subject is required.
        /// </summary>
        internal static string MsgEmailSubjectRequired {
            get {
                return ResourceManager.GetString("MsgEmailSubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway configuration is saved successfully.
        /// </summary>
        internal static string MsgGatewayConfigSaved {
            get {
                return ResourceManager.GetString("MsgGatewayConfigSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1 gateway must be selected.
        /// </summary>
        internal static string MsgGatewayMustBeSelected {
            get {
                return ResourceManager.GetString("MsgGatewayMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway name {0} is already in use.
        /// </summary>
        internal static string MsgGatewayNameAlreadyExists {
            get {
                return ResourceManager.GetString("MsgGatewayNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway is being started now.
        /// </summary>
        internal static string MsgGatewayStarting {
            get {
                return ResourceManager.GetString("MsgGatewayStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator group cannot be modified.
        /// </summary>
        internal static string MsgGroupNameCannotEdit {
            get {
                return ResourceManager.GetString("MsgGroupNameCannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name must be unique.
        /// </summary>
        internal static string MsgGroupNameNotUnique {
            get {
                return ResourceManager.GetString("MsgGroupNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group is saved successfully.
        /// </summary>
        internal static string MsgGroupSaved {
            get {
                return ResourceManager.GetString("MsgGroupSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Message Details.
        /// </summary>
        internal static string MsgHideMessageDetails {
            get {
                return ResourceManager.GetString("MsgHideMessageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensee cannot be empty.
        /// </summary>
        internal static string MsgLicenseeRequired {
            get {
                return ResourceManager.GetString("MsgLicenseeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing information is saved.
        /// </summary>
        internal static string MsgLicenseInformationSaved {
            get {
                return ResourceManager.GetString("MsgLicenseInformationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License key cannot be empty.
        /// </summary>
        internal static string MsgLicenseKeyRequired {
            get {
                return ResourceManager.GetString("MsgLicenseKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login name is not unique.
        /// </summary>
        internal static string MsgLoginNameNotUnique {
            get {
                return ResourceManager.GetString("MsgLoginNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login name is required.
        /// </summary>
        internal static string MsgLoginNameRequired {
            get {
                return ResourceManager.GetString("MsgLoginNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is archived.
        /// </summary>
        internal static string MsgMessageArchived {
            get {
                return ResourceManager.GetString("MsgMessageArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is deleted from storage.
        /// </summary>
        internal static string MsgMessageDeleted {
            get {
                return ResourceManager.GetString("MsgMessageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messenger configuration is saved successfully.
        /// </summary>
        internal static string MsgMessengerConfigSaved {
            get {
                return ResourceManager.GetString("MsgMessengerConfigSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1 messenger must be selected.
        /// </summary>
        internal static string MsgMessengerMustBeSelected {
            get {
                return ResourceManager.GetString("MsgMessengerMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messenger name {0} is already in use.
        /// </summary>
        internal static string MsgMessengerNameAlreadyExists {
            get {
                return ResourceManager.GetString("MsgMessengerNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message column name or default text message is required.
        /// </summary>
        internal static string MsgMsgColDefaultMsgRequired {
            get {
                return ResourceManager.GetString("MsgMsgColDefaultMsgRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} messages are created successfully.
        /// </summary>
        internal static string MsgMultipleMessagesCreated {
            get {
                return ResourceManager.GetString("MsgMultipleMessagesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string MsgNameRequired {
            get {
                return ResourceManager.GetString("MsgNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No channel is selected.
        /// </summary>
        internal static string MsgNoChannelSelected {
            get {
                return ResourceManager.GetString("MsgNoChannelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message to display.
        /// </summary>
        internal static string MsgNoMessageToDisplay {
            get {
                return ResourceManager.GetString("MsgNoMessageToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messenger is selected.
        /// </summary>
        internal static string MsgNoMessengerSelected {
            get {
                return ResourceManager.GetString("MsgNoMessengerSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string MsgNow {
            get {
                return ResourceManager.GetString("MsgNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered passwords do not match.
        /// </summary>
        internal static string MsgPasswordNotMatched {
            get {
                return ResourceManager.GetString("MsgPasswordNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string MsgPasswordRequired {
            get {
                return ResourceManager.GetString("MsgPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1 recipient must be specified.
        /// </summary>
        internal static string MsgRecipientsRequired {
            get {
                return ResourceManager.GetString("MsgRecipientsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all system settings?.
        /// </summary>
        internal static string MsgResetSettings {
            get {
                return ResourceManager.GetString("MsgResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes before exiting?.
        /// </summary>
        internal static string MsgSaveChangesBeforeExit {
            get {
                return ResourceManager.GetString("MsgSaveChangesBeforeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender email is required.
        /// </summary>
        internal static string MsgSenderEmailRequired {
            get {
                return ResourceManager.GetString("MsgSenderEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Message Details.
        /// </summary>
        internal static string MsgShowMessageDetails {
            get {
                return ResourceManager.GetString("MsgShowMessageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 message is created successfully.
        /// </summary>
        internal static string MsgSingleMessageCreated {
            get {
                return ResourceManager.GetString("MsgSingleMessageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP user name and password are required.
        /// </summary>
        internal static string MsgSmtpInformationRequired {
            get {
                return ResourceManager.GetString("MsgSmtpInformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP server is required.
        /// </summary>
        internal static string MsgSmtpServerRequired {
            get {
                return ResourceManager.GetString("MsgSmtpServerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status column name is required.
        /// </summary>
        internal static string MsgStatusColNameRequired {
            get {
                return ResourceManager.GetString("MsgStatusColNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        internal static string MsgTypeSms {
            get {
                return ResourceManager.GetString("MsgTypeSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique message id column name is required.
        /// </summary>
        internal static string MsgUniqMsgIdColNameRequired {
            get {
                return ResourceManager.GetString("MsgUniqMsgIdColNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique name must be specified.
        /// </summary>
        internal static string MsgUniqueNameRequired {
            get {
                return ResourceManager.GetString("MsgUniqueNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is required.
        /// </summary>
        internal static string MsgURLRequired {
            get {
                return ResourceManager.GetString("MsgURLRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator user cannot be modified.
        /// </summary>
        internal static string MsgUserCannotEdit {
            get {
                return ResourceManager.GetString("MsgUserCannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is saved successfully.
        /// </summary>
        internal static string MsgUserSaved {
            get {
                return ResourceManager.GetString("MsgUserSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical path to the web application is required.
        /// </summary>
        internal static string MsgWebServerPathRequired {
            get {
                return ResourceManager.GetString("MsgWebServerPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web server port must be greater than 0.
        /// </summary>
        internal static string MsgWebServerPortRequired {
            get {
                return ResourceManager.GetString("MsgWebServerPortRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual path is required.
        /// </summary>
        internal static string MsgWebServerVirtualPathRequired {
            get {
                return ResourceManager.GetString("MsgWebServerVirtualPathRequired", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap newmessage {
            get {
                object obj = ResourceManager.GetObject("newmessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newmessage1 {
            get {
                object obj = ResourceManager.GetObject("newmessage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap outbox {
            get {
                object obj = ResourceManager.GetObject("outbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSM.
        /// </summary>
        internal static string ProtocolTypeGsm {
            get {
                return ResourceManager.GetString("ProtocolTypeGsm", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap refresh_view {
            get {
                object obj = ResourceManager.GetObject("refresh_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string ScheduledNow {
            get {
                return ResourceManager.GetString("ScheduledNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is already started.
        /// </summary>
        internal static string ServiceAlreadyStarted {
            get {
                return ResourceManager.GetString("ServiceAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is already stopped.
        /// </summary>
        internal static string ServiceAlreadyStopped {
            get {
                return ResourceManager.GetString("ServiceAlreadyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to start.
        /// </summary>
        internal static string ServiceAttempStart {
            get {
                return ResourceManager.GetString("ServiceAttempStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to stop.
        /// </summary>
        internal static string ServiceAttemptStop {
            get {
                return ResourceManager.GetString("ServiceAttemptStop", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap services {
            get {
                object obj = ResourceManager.GetObject("services", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system {
            get {
                object obj = ResourceManager.GetObject("system", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tool {
            get {
                object obj = ResourceManager.GetObject("tool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap users {
            get {
                object obj = ResourceManager.GetObject("users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap webinterface {
            get {
                object obj = ResourceManager.GetObject("webinterface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
